// <auto-generated />
using GeekBurger.LabelLoader.Migrations;
using GeekBurger.LabelLoader.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeekBurger.LabelLoader.Migrations.Migrations
{
    [DbContext(typeof(LabelContext))]
    [Migration("20191104231447_Criando tabela de nutrientes")]
    partial class Criandotabeladenutrientes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeekBurger.LabelLoader.Models.TabelaNutrientes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .HasColumnName("Descricao")
                        .HasColumnType("varchar(60)");

                    b.HasKey("Id");

                    b.ToTable("Cad_Ingredientes");
                });

            modelBuilder.Entity<TabelaNutrientes>().HasData(
                new TabelaNutrientes(1, "Carboidratos"),
                new TabelaNutrientes(2, "Proteínas"),
                new TabelaNutrientes(3, "Gorduras Totais"),
                new TabelaNutrientes(4, "Gorduras Saturadas"),
                new TabelaNutrientes(5, "Gorduras Trans"),
                new TabelaNutrientes(6, "Fibra Alimentar"),
                new TabelaNutrientes(8, "Sódio"),
                new TabelaNutrientes(9, "Proteína"),
                new TabelaNutrientes(10, "Lipídeos"),
                new TabelaNutrientes(11, "Colesterol"),
                new TabelaNutrientes(12, "Carboidratos"),
                new TabelaNutrientes(13, "Alimentar"),
                new TabelaNutrientes(14, "Cinzas"),
                new TabelaNutrientes(15, "Cálcio"),
                new TabelaNutrientes(16, "Magnésio"),
                new TabelaNutrientes(17, "Número do Manganês"),
                new TabelaNutrientes(18, "Fósforo Ferro"),
                new TabelaNutrientes(19, "Sódio"),
                new TabelaNutrientes(20, "Potássio"),
                new TabelaNutrientes(21, "Cobre"),
                new TabelaNutrientes(22, "Zinco"),
                new TabelaNutrientes(23, "Retinol"),
                new TabelaNutrientes(24, "RE"),
                new TabelaNutrientes(25, "RAE"),
                new TabelaNutrientes(26, "Tiamina"),
                new TabelaNutrientes(27, "Riboflavina"),
                new TabelaNutrientes(28, "Piridoxina"),
                new TabelaNutrientes(29, "Niacina"),
                new TabelaNutrientes(30, "Vitamina C")


                );

                



 

 




#pragma warning restore 612, 618
        }
    }
}
